---
- name: Configure Appoptics managed configuration file
  template:
    src: config.yaml.j2
    dest: "{{ appoptics_config_file_path }}"
    owner: "{{ appoptics_user }}"
    group: "{{ __appoptics_group }}"
    mode: "{{ __appoptics_files_mode }}"
  notify: restart appoptics
  when: appoptics_managed_config_file | bool

- name: Configure Appoptics plugins
  copy:
    dest: "{{ __appoptics_plugins_config_path }}/{{ item.file_name }}"
    owner: "{{ __appoptics_user }}"
    group: "{{ __appoptics_group }}"
    content: "{{ item.content | to_nice_yaml(indent=2) }}"
  when: item.file_name | length and item.content | length
  loop: "{{ appoptics_plugins }}"

- name: Configure Appoptics tasks
  copy:
    dest: "{{ __appoptics_tasks_config_path }}/{{ item.file_name }}"
    owner: "{{ __appoptics_user }}"
    group: "{{ __appoptics_group }}"
    content: "{{ item.content | to_nice_yaml(indent=2) }}"
  when: item.file_name | length and item.content | length
  loop: "{{ appoptics_tasks }}"
