---
- name: Set ansible distribution version
  set_fact:
    distro_version: "{{ ansible_distribution_major_version }}"

- name: Set ansible distribution version for Amazon linux 1
  set_fact:
    distro_version: "6"
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "NA"

- name: Set ansible distribution version for Amazon linux 2
  set_fact:
    distro_version: "7"
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
